services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /rails
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/lezvaget_development
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bash

volumes:
  db-data:
